[project]
name = "complaints-n8n-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi[all]>=0.115.12",
    "sqlalchemy>=2.0.40",
    "translate>=3.6.1",
]
